const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTES_PRODUCT",
  GO_TO_CART: "GO_TO_CART",
  CHECKOUT: "CHECKOUT",
  GO_TO_STORE: "GO_TO_STORE",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_QTY: "REMOVE_QTY",
};

export default ActionTypes;
